/** SPEC-US §4.2 / §4.7 defaults */
export const DEFAULT_K401_ANNUAL_RETURN_PCT = 7;
export const DEFAULT_EARLY_WITHDRAWAL_PENALTY_PCT = 10;
export const DEFAULT_EARLY_WITHDRAWAL_TAX_WITHHOLDING_PCT = 22;
export const DEFAULT_EMPLOYER_MATCH_RATE_PCT = 50;
export const DEFAULT_EMPLOYER_MATCH_CAP_PCT = 6;
export const K401_TRANCHE_FRACTION = 0.5;
